# ==============================================================================
#  Title: Gene-Wise TCGA Survival Analysis
#  2026-06-23 | Shiwoo Koak | Seoul National University
#
#  Description:
#    Perform gene-wise overall survival (OS) analysis using TCGA log2(TPM + 1)
#    RNA-seq expression, raw counts, and clinical data generated by
#    01_download_tcga.R. Samples and genes are filtered before age-adjusted Cox
#    modeling. Sex is included as an additional covariate when both sex levels
#    are present.
#    Supports either continuous gene expression or median high/low grouping.
#
#  Usage:
#    Rscript src/02_gene_survival_analysis.R <cancer_type> [method]
#
#  Methods:
#    median      Age-adjusted Cox model using a 50% median high/low expression
#                split. Sex is included when both sex levels are present.
#                Default if no method is provided.
#    continuous  Age-adjusted Cox model using expression as a continuous
#                variable. Sex is included when both sex levels are present.
#
#  Output:
#    data/<cancer_type>_coxph_<method>.tsv
# ==============================================================================

################################################################################
# Step 0: Load Packages --------------------------------------------------------
################################################################################

library(dplyr)
library(readr)
library(survival)

################################################################################
# Step 1: Utilities ------------------------------------------------------------
################################################################################

normalize_patient_barcode <- function(x) {
  substr(x, 1, 12)
}

calculate_mad <- function(x) {
  median(abs(x - median(x, na.rm = TRUE)), na.rm = TRUE)
}

################################################################################
# Step 2: Prepare and Filter Input Data ----------------------------------------
################################################################################

filter_samples <- function(expression_data, counts_data, clinical_data) {
  
  sample_cols <- grep("^TCGA-", colnames(expression_data), value = TRUE)
  metadata_cols <- setdiff(colnames(expression_data), sample_cols)
  
  message("  - Samples in expression/counts data: ", length(sample_cols))
  
  sample_cols <- sample_cols[substr(sample_cols, 14, 16) == "01A"]
  message("  - Primary tumor samples (01A): ", length(sample_cols))
  
  survival_data <- clinical_data %>%
    transmute(
      patient = normalize_patient_barcode(sample),
      age     = as.numeric(age),
      sex     = sex,
      OS.time = as.numeric(OS.time),
      OS      = as.integer(OS)
    )
  
  sample_info <- data.frame(
    sample  = sample_cols,
    patient = normalize_patient_barcode(sample_cols),
    stringsAsFactors = FALSE
  ) %>%
    arrange(sample) %>%
    left_join(survival_data, by = "patient") %>%
    na.omit()
  
  message("  - Primary tumor samples with survival, age, and sex data: ", nrow(sample_info))
  
  if (nrow(sample_info) == 0) {
    stop(
      "No primary tumor samples matched the clinical survival data.",
      call. = FALSE
    )
  }
  
  counts_matrix <- as.matrix(counts_data[, sample_info$sample])
  storage.mode(counts_matrix) <- "numeric"
  
  library_sizes <- colSums(counts_matrix, na.rm = TRUE)
  log2_library_sizes <- log2(library_sizes)
  
  library_median <- median(log2_library_sizes, na.rm = TRUE)
  library_mad    <- calculate_mad(log2_library_sizes)
  library_cutoff <- library_median - 3 * library_mad
  
  n_before_library_filter <- nrow(sample_info)
  
  sample_info <- sample_info %>%
    mutate(
      library_size      = library_sizes[sample],
      log2_library_size = log2_library_sizes[sample]
    ) %>%
    filter(
      is.finite(log2_library_size),
      log2_library_size >= library_cutoff
    )
  
  message(
    "  - Samples after library-size filtering: ",
    nrow(sample_info),
    " (removed ",
    n_before_library_filter - nrow(sample_info),
    ")"
  )
  
  if (nrow(sample_info) == 0) {
    stop(
      "No samples remained after library-size filtering.",
      call. = FALSE
    )
  }
  
  sample_cols <- sample_info$sample
  
  list(
    expression_data = expression_data %>%
      dplyr::select(all_of(metadata_cols), all_of(sample_cols)),
    counts_data = counts_data %>%
      dplyr::select(all_of(metadata_cols), all_of(sample_cols)),
    survival_data = sample_info %>%
      dplyr::select(sample, patient, age, sex, OS.time, OS)
  )
}

filter_genes <- function(expression_data, counts_data) {
  
  message("  - Genes in expression/counts data: ", nrow(expression_data))
  
  sample_cols <- grep("^TCGA-", colnames(counts_data), value = TRUE)
  
  expression_matrix <- as.matrix(expression_data[, sample_cols])
  counts_matrix     <- as.matrix(counts_data[, sample_cols])
  
  storage.mode(expression_matrix) <- "numeric"
  storage.mode(counts_matrix)     <- "numeric"
  
  protein_coding_genes <- expression_data$gene_type == "protein_coding"
  protein_coding_genes[is.na(protein_coding_genes)] <- FALSE
  message("  - Protein-coding genes: ", sum(protein_coding_genes, na.rm = TRUE))
  
  expression_data   <- expression_data[protein_coding_genes, ]
  counts_data       <- counts_data[protein_coding_genes, ]
  expression_matrix <- expression_matrix[protein_coding_genes, , drop = FALSE]
  counts_matrix     <- counts_matrix[protein_coding_genes, , drop = FALSE]
  
  min_samples <- ceiling(0.20 * length(sample_cols))
  count_filter <- rowSums(counts_matrix >= 15, na.rm = TRUE) >= min_samples
  
  message(
    "  - Genes with >=15 raw counts in at least 20% of samples: ",
    sum(count_filter, na.rm = TRUE)
  )
  
  if (sum(count_filter, na.rm = TRUE) == 0) {
    stop("No genes remained after count-based filtering.", call. = FALSE)
  }
  
  list(
    expression_data = expression_data[count_filter, ],
    counts_data = counts_data[count_filter, ]
  )
}

prepare_analysis_data <- function(expression_data, counts_data, clinical_data) {
  
  sample_filtered <- filter_samples(
    expression_data = expression_data,
    counts_data     = counts_data,
    clinical_data   = clinical_data
  )
  
  gene_filtered <- filter_genes(
    expression_data = sample_filtered$expression_data,
    counts_data     = sample_filtered$counts_data
  )
  
  expression_data <- gene_filtered$expression_data
  sample_cols <- grep("^TCGA-", colnames(expression_data), value = TRUE)
  
  expression_matrix <- as.matrix(expression_data[, sample_cols])
  storage.mode(expression_matrix) <- "numeric"
  
  list(
    gene_metadata     = expression_data[, c("gene_name", "gene_id", "gene_type")],
    expression_matrix = expression_matrix,
    survival_data     = sample_filtered$survival_data
  )
}

################################################################################
# Step 3: Single-Gene Survival Analysis ----------------------------------------
################################################################################

fit_cox_model <- function(model_formula, model_data, term_name) {
  
  cox_fit <- tryCatch(
    suppressWarnings(
      coxph(model_formula, data = model_data)
    ),
    error = function(e) NULL
  )
  
  if (is.null(cox_fit)) return(NULL)
  
  coef_summary <- summary(cox_fit)$coefficients
  
  if (!term_name %in% rownames(coef_summary)) return(NULL)
  
  cox_coef <- coef_summary[term_name, "coef"]
  se_value <- coef_summary[term_name, "se(coef)"]
  hr_value <- coef_summary[term_name, "exp(coef)"]
  p_value  <- coef_summary[term_name, "Pr(>|z|)"]
  
  if (
    !is.finite(cox_coef) ||
      !is.finite(se_value) ||
      !is.finite(hr_value) ||
      !is.finite(p_value)
  ) {
    return(NULL)
  }
  
  data.frame(
    cox_coef = cox_coef,
    se       = se_value,
    HR       = hr_value,
    pvalue   = p_value
  )
}

analyze_gene <- function(expression_level, survival_data, method) {
  
  gene_data <- data.frame(
    OS.time          = survival_data$OS.time,
    OS               = survival_data$OS,
    age              = survival_data$age,
    sex              = survival_data$sex,
    expression_level = as.numeric(expression_level)
  ) %>%
    mutate(
      age = as.numeric(age),
      sex = factor(sex)
    ) %>%
    filter(
      !is.na(OS.time),
      !is.na(OS),
      is.finite(age),
      !is.na(sex),
      !is.na(expression_level)
    ) %>%
    droplevels()
  
  if (nrow(gene_data) < 10) return(NULL)
  if (length(unique(gene_data$OS)) < 2) return(NULL)
  if (length(unique(gene_data$expression_level)) < 2) return(NULL)
  
  n_samples <- nrow(gene_data)
  n_events  <- sum(gene_data$OS == 1)
  adjust_for_sex <- nlevels(gene_data$sex) >= 2
  
  if (method == "continuous") {
    model_formula <- if (adjust_for_sex) {
      Surv(OS.time, OS) ~ expression_level + age + sex
    } else {
      Surv(OS.time, OS) ~ expression_level + age
    }
    
    gene_result <- fit_cox_model(
      model_formula = model_formula,
      model_data    = gene_data,
      term_name     = "expression_level"
    )
    
    if (is.null(gene_result)) return(NULL)
    
    gene_result %>%
      mutate(
        method    = method,
        cutoff    = NA_real_,
        n_samples = n_samples,
        n_events  = n_events
      )
  } else {
    cutoff_value <- median(gene_data$expression_level, na.rm = TRUE)
    
    gene_data <- gene_data %>%
      mutate(
        expression_group = factor(
          ifelse(expression_level > cutoff_value, "High", "Low"),
          levels = c("Low", "High")
        )
      )
    
    if (length(unique(gene_data$expression_group)) < 2) return(NULL)
    
    model_formula <- if (adjust_for_sex) {
      Surv(OS.time, OS) ~ expression_group + age + sex
    } else {
      Surv(OS.time, OS) ~ expression_group + age
    }
    
    gene_result <- fit_cox_model(
      model_formula = model_formula,
      model_data    = gene_data,
      term_name     = "expression_groupHigh"
    )
    
    if (is.null(gene_result)) return(NULL)
    
    gene_result %>%
      mutate(
        method    = method,
        cutoff    = cutoff_value,
        n_samples = n_samples,
        n_events  = n_events
      )
  }
}

################################################################################
# Step 4: Run Survival Analysis ------------------------------------------------
################################################################################

run_survival <- function(gene_metadata, expression_matrix, survival_data, method) {
  
  message("Running gene-wise Cox models...")
  message("  - Cox adjustment covariates: age + sex when both sex levels are present")
  
  results_list <- lapply(seq_len(nrow(expression_matrix)), function(i) {
    
    gene_result <- analyze_gene(
      expression_level = expression_matrix[i, ],
      survival_data    = survival_data,
      method           = method
    )
    
    if (is.null(gene_result)) return(NULL)
    
    bind_cols(
      gene_metadata[i, , drop = FALSE],
      gene_result
    )
  })
  
  valid_results <- results_list[!vapply(results_list, is.null, logical(1))]
  
  if (length(valid_results) == 0) {
    stop("No genes produced valid Cox model results.", call. = FALSE)
  }
  
  results_df <- bind_rows(valid_results) %>%
    mutate(FDR = p.adjust(pvalue, method = "BH")) %>%
    arrange(FDR, pvalue) %>%
    select(gene_name, gene_id, cox_coef, se, HR, pvalue, FDR, n_samples, n_events)
  
  results_df
}

################################################################################
# Step 5: Main Execution -------------------------------------------------------
################################################################################

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)

if (length(args) < 1 || length(args) > 2) {
  stop("Usage: Rscript src/02_gene_survival_analysis.R <cancer_type> [method]")
}

cancer_type <- toupper(args[1])
method <- ifelse(length(args) == 2, tolower(args[2]), "median")

if (!method %in% c("median", "continuous")) {
  stop("Method must be either 'median' or 'continuous'.", call. = FALSE)
}

input_dir <- file.path("data", paste0("TCGA_", cancer_type))
output_dir <- "data"

expression_file <- file.path(
  input_dir,
  paste0(cancer_type, "_rnaseq_log2tpm.tsv")
)

counts_file <- file.path(
  input_dir,
  paste0(cancer_type, "_rnaseq_counts.tsv")
)

clinical_file <- file.path(
  input_dir,
  paste0(cancer_type, "_clinical.tsv")
)

message(paste("Starting gene-wise survival analysis for", cancer_type))
message(paste("Input directory:", input_dir))
message(paste("Output directory:", output_dir))

message("Loading input data...")
expression_data <- read_tsv(expression_file, show_col_types = FALSE)
counts_data     <- read_tsv(counts_file, show_col_types = FALSE)
clinical_data   <- read_tsv(clinical_file, show_col_types = FALSE)

analysis_data <- prepare_analysis_data(
  expression_data = expression_data,
  counts_data     = counts_data,
  clinical_data   = clinical_data
)

message("  - Final samples for survival analysis: ", nrow(analysis_data$survival_data))
message("  - Final genes for survival analysis: ", nrow(analysis_data$expression_matrix))
message("  - Survival method: ", method)

results_df <- run_survival(
  gene_metadata     = analysis_data$gene_metadata,
  expression_matrix = analysis_data$expression_matrix,
  survival_data     = analysis_data$survival_data,
  method            = method
)

if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

output_path <- file.path(
  output_dir,
  paste0(cancer_type, "_coxph_", method, ".tsv")
)

write_tsv(results_df, output_path)

message("Saved survival results to: ", output_path)
message("Pipeline complete!")
