# ==============================================================================
#  Title: Run GSEA from Gene-Wise Survival Results
#  2026-06-23 | Shiwoo Koak | Seoul National University
#
#  Description:
#    Run Gene Set Enrichment Analysis (GSEA) using gene-wise survival results
#    generated by 02_gene_survival_analysis.R. The ranking metric is calculated
#    from Cox coefficients and p-values over Ensembl gene IDs. This script runs
#    GSEA for KEGG, Reactome, Hallmark, and Gene Ontology (GO BP, GO MF, and
#    GO CC). KEGG and Reactome use Entrez ID-converted ranked genes, while
#    Hallmark and GO use Ensembl gene IDs directly. Core enrichment genes are
#    converted to gene symbols in the output tables.
#
#  Usage:
#    Rscript src/03_run_gsea.R <survival_file>
#
#  Output:
#    data/<survival_file_basename>_gsea_kegg.tsv
#    data/<survival_file_basename>_gsea_reactome.tsv
#    data/<survival_file_basename>_gsea_hallmark.tsv
#    data/<survival_file_basename>_gsea_gobp.tsv
#    data/<survival_file_basename>_gsea_gomf.tsv
#    data/<survival_file_basename>_gsea_gocc.tsv
# ==============================================================================

################################################################################
# Step 0: Load Packages --------------------------------------------------------
################################################################################

library(dplyr)
library(readr)
library(tools)
library(clusterProfiler)
library(ReactomePA)
library(msigdbr)
library(org.Hs.eg.db)
library(GO.db)

set.seed(1)

################################################################################
# Step 1: Utilities ------------------------------------------------------------
################################################################################

create_rank_metric <- function(survival_data) {
  
  rank_data <- survival_data %>%
    mutate(
      ensembl_id = sub("\\..*$", "", gene_id),
      score = -log10(pvalue) * sign(cox_coef)
    ) %>%
    filter(!is.na(ensembl_id), ensembl_id != "", is.finite(score))
  
  if (nrow(rank_data) == 0) {
    stop("No valid genes remained after creating the GSEA ranking metric.")
  }
  
  rank_data <- rank_data %>%
    group_by(ensembl_id) %>%
    slice_max(order_by = abs(score), n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    arrange(desc(score)) %>%
    dplyr::select(ensembl_id, score)
  
  gene_list <- rank_data$score
  names(gene_list) <- rank_data$ensembl_id
  
  gene_list
}

ensembl_to_entrez <- function(gene_list) {
  
  if (is.null(names(gene_list)) || any(is.na(names(gene_list)) | names(gene_list) == "")) {
    stop("The ranked gene list must be named with Ensembl gene IDs.")
  }
  
  ensembl_ids <- names(gene_list)
  
  entrez_ids <- unname(
    AnnotationDbi::mapIds(
      org.Hs.eg.db,
      keys      = ensembl_ids,
      column    = "ENTREZID",
      keytype   = "ENSEMBL",
      multiVals = "first"
    )
  )
  
  rank_data <- data.frame(
    entrez_id = entrez_ids,
    score     = unname(gene_list),
    stringsAsFactors = FALSE
  ) %>%
    filter(!is.na(entrez_id), entrez_id != "", is.finite(score)) %>%
    group_by(entrez_id) %>%
    slice_max(order_by = abs(score), n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    arrange(desc(score)) %>%
    dplyr::select(entrez_id, score)
  
  if (nrow(rank_data) == 0) {
    stop("No genes could be mapped from Ensembl IDs to Entrez IDs.")
  }
  
  entrez_gene_list <- rank_data$score
  names(entrez_gene_list) <- rank_data$entrez_id
  
  entrez_gene_list
}

convert_core_enrichment <- function(gsea_df, keytype = "ENTREZID") {
  
  if (nrow(gsea_df) == 0 || !"core_enrichment" %in% colnames(gsea_df)) {
    return(gsea_df)
  }
  
  core_gene_list <- strsplit(
    ifelse(is.na(gsea_df$core_enrichment), "", gsea_df$core_enrichment),
    split = "/",
    fixed = TRUE
  )
  
  gene_ids <- unique(unlist(core_gene_list, use.names = FALSE))
  gene_ids <- gene_ids[!is.na(gene_ids) & gene_ids != ""]
  
  if (length(gene_ids) == 0) {
    return(gsea_df)
  }
  
  gene_symbols <- unname(
    AnnotationDbi::mapIds(
      org.Hs.eg.db,
      keys      = gene_ids,
      column    = "SYMBOL",
      keytype   = keytype,
      multiVals = "first"
    )
  )
  names(gene_symbols) <- gene_ids
  
  convert_gene_ids <- function(ids) {
    
    ids <- ids[!is.na(ids) & ids != ""]
    
    if (length(ids) == 0) {
      return(NA_character_)
    }
    
    symbols <- gene_symbols[ids]
    symbols[is.na(symbols)] <- ids[is.na(symbols)]
    
    paste(unname(symbols), collapse = "/")
  }
  
  gsea_df$core_enrichment <- vapply(
    core_gene_list,
    convert_gene_ids,
    character(1)
  )
  
  gsea_df
}

clean_hallmark_name <- function(term_id) {
  
  term_name <- sub("^HALLMARK_", "", term_id)
  gsub("_", " ", term_name)
}

get_hallmark_gene_sets <- function() {
  
  hallmark_data <- msigdbr::msigdbr(
    species    = "Homo sapiens",
    collection = "H"
  ) %>%
    transmute(
      ID          = gs_name,
      Description = clean_hallmark_name(gs_name),
      ensembl     = ensembl_gene
    ) %>%
    filter(!is.na(ensembl), ensembl != "") %>%
    distinct()
  
  if (nrow(hallmark_data) == 0) {
    stop("No Hallmark Ensembl genes were found from msigdbr.")
  }
  
  term2gene <- hallmark_data %>%
    distinct(ID, ensembl)
  
  term2name <- hallmark_data %>%
    distinct(ID, Description)
  
  term_names <- term2name$Description
  names(term_names) <- term2name$ID
  
  list(
    term2gene = term2gene,
    term2name = term2name,
    term_names = term_names
  )
}

get_go_descriptions <- function(ids) {
  
  go_terms <- GO.db::GOTERM[ids]
  descriptions <- unname(AnnotationDbi::Term(go_terms))
  names(descriptions) <- ids
  
  descriptions
}

get_kegg_descriptions <- function(ids) {
  
  kegg_data <- clusterProfiler::download_KEGG(
    species  = "hsa",
    keggType = "KEGG",
    keyType  = "ncbi-geneid"
  )
  
  descriptions <- kegg_data$KEGGPATHID2NAME$to
  names(descriptions) <- kegg_data$KEGGPATHID2NAME$from
  
  descriptions[ids]
}

get_reactome_descriptions <- function(ids) {
  
  reactome_data <- ReactomePA::gson_Reactome("human")
  descriptions <- reactome_data@gsid2name$name
  names(descriptions) <- reactome_data@gsid2name$gsid
  
  descriptions[ids]
}

repair_gsea_metadata <- function(gsea_fit, gsea_df, ontology, description_fun) {
  
  if (nrow(gsea_df) == 0) {
    return(gsea_df)
  }
  
  if (!"ONTOLOGY" %in% colnames(gsea_df)) {
    gsea_df <- gsea_df %>%
      mutate(ONTOLOGY = ontology, .before = ID)
  }
  
  missing_rows <- which(is.na(gsea_df$ID))
  
  if (length(missing_rows) == 0) {
    return(gsea_df)
  }
  
  gene_set_sizes <- vapply(gsea_fit@geneSets, length, integer(1))
  min_gs_size <- gsea_fit@params$minGSSize
  max_gs_size <- gsea_fit@params$maxGSSize
  
  result_ids <- gsea_df$ID[!is.na(gsea_df$ID)]
  missing_ids <- setdiff(names(gsea_fit@geneSets), result_ids)
  missing_ids <- missing_ids[
    gene_set_sizes[missing_ids] >= min_gs_size &
      gene_set_sizes[missing_ids] <= max_gs_size
  ]
  
  n_fill <- min(length(missing_rows), length(missing_ids))
  
  if (n_fill == 0) {
    return(gsea_df)
  }
  
  fill_rows <- missing_rows[seq_len(n_fill)]
  fill_ids  <- missing_ids[seq_len(n_fill)]
  descriptions <- description_fun(fill_ids)
  
  gsea_df$ONTOLOGY[fill_rows]    <- ontology
  gsea_df$ID[fill_rows]          <- fill_ids
  gsea_df$Description[fill_rows] <- unname(descriptions[fill_ids])
  gsea_df$setSize[fill_rows]     <- gene_set_sizes[fill_ids]
  
  message("  - Recovered metadata for ", n_fill, " ", ontology, " terms with NA statistics")
  
  gsea_df
}

format_gsea_result <- function(gsea_fit, ontology, description_fun, core_keytype = "ENTREZID") {
  
  gsea_df <- as.data.frame(gsea_fit)
  
  if (nrow(gsea_df) == 0) {
    return(gsea_df)
  }
  
  gsea_df <- repair_gsea_metadata(
    gsea_fit        = gsea_fit,
    gsea_df         = gsea_df,
    ontology        = ontology,
    description_fun = description_fun
  )
  
  gsea_df %>%
    arrange(p.adjust, desc(NES)) %>%
    convert_core_enrichment(keytype = core_keytype) %>%
    dplyr::select(ONTOLOGY, ID, Description, setSize, everything())
}

save_gsea_result <- function(gsea_df, output_dir, survival_name, suffix) {
  
  output_path <- file.path(output_dir, paste0(survival_name, "_", suffix, ".tsv"))
  write_tsv(gsea_df, output_path)
  message("Saved ", suffix, " results to: ", output_path)
}

################################################################################
# Step 2: Run GSEA -------------------------------------------------------------
################################################################################

run_gsea_hallmark <- function(gene_list) {
  
  message("Running clusterProfiler GSEA: Hallmark")
  message("  - Ranked Ensembl genes: ", length(gene_list))
  
  hallmark_sets <- get_hallmark_gene_sets()
  
  message("  - Hallmark gene sets: ", n_distinct(hallmark_sets$term2gene$ID))
  
  gsea_fit <- clusterProfiler::GSEA(
    geneList     = gene_list,
    TERM2GENE    = hallmark_sets$term2gene,
    TERM2NAME    = hallmark_sets$term2name,
    pvalueCutoff = 1,
    verbose      = FALSE
  )
  
  format_gsea_result(
    gsea_fit        = gsea_fit,
    ontology        = "Hallmark",
    description_fun = function(ids) hallmark_sets$term_names[ids],
    core_keytype    = "ENSEMBL"
  )
}

run_gsea_reactome <- function(gene_list) {
  
  message("Running ReactomePA gsePathway")
  entrez_gene_list <- ensembl_to_entrez(gene_list)
  message("  - Ranked Entrez genes: ", length(entrez_gene_list))
  
  gsea_fit <- ReactomePA::gsePathway(
    geneList     = entrez_gene_list,
    organism     = "human",
    pvalueCutoff = 1,
    verbose      = FALSE
  )
  
  format_gsea_result(
    gsea_fit        = gsea_fit,
    ontology        = "Reactome",
    description_fun = get_reactome_descriptions,
    core_keytype    = "ENTREZID"
  )
}

run_gsea_kegg <- function(gene_list) {
  
  message("Running clusterProfiler gseKEGG")
  entrez_gene_list <- ensembl_to_entrez(gene_list)
  message("  - Ranked Entrez genes: ", length(entrez_gene_list))
  
  gsea_fit <- gseKEGG(
    geneList     = entrez_gene_list,
    organism     = "hsa",
    keyType      = "ncbi-geneid",
    pvalueCutoff = 1,
    verbose      = FALSE
  )
  
  format_gsea_result(
    gsea_fit        = gsea_fit,
    ontology        = "KEGG",
    description_fun = get_kegg_descriptions,
    core_keytype    = "ENTREZID"
  )
}

run_gsea_go <- function(gene_list, ontology) {
  
  message("Running clusterProfiler gseGO: ", ontology)
  message("  - Ranked Ensembl genes: ", length(gene_list))
  
  gsea_fit <- gseGO(
    geneList     = gene_list,
    OrgDb        = org.Hs.eg.db,
    keyType      = "ENSEMBL",
    ont          = ontology,
    pvalueCutoff = 1,
    verbose      = FALSE
  )
  
  format_gsea_result(
    gsea_fit        = gsea_fit,
    ontology        = ontology,
    description_fun = get_go_descriptions,
    core_keytype    = "ENSEMBL"
  )
}

################################################################################
# Step 3: Main Execution -------------------------------------------------------
################################################################################

# Parse command line arguments
args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 1) {
  stop("Usage: Rscript src/03_run_gsea.R <survival_file>")
}

survival_file <- args[1]
output_dir    <- "data"

message("Starting GSEA analysis")
message("Survival file: ", survival_file)
message("Output directory: ", output_dir)

message("Loading survival results...")
survival_data <- read_tsv(survival_file, show_col_types = FALSE)

message("Creating ranked gene list...")
gene_list <- create_rank_metric(survival_data)
message("Ranked Ensembl genes: ", length(gene_list))

if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)

survival_name <- file_path_sans_ext(basename(survival_file))

hallmark_df <- run_gsea_hallmark(gene_list)
save_gsea_result(hallmark_df, output_dir, survival_name, "gsea_hallmark")

reactome_df <- run_gsea_reactome(gene_list)
save_gsea_result(reactome_df, output_dir, survival_name, "gsea_reactome")

kegg_df <- run_gsea_kegg(gene_list)
save_gsea_result(kegg_df, output_dir, survival_name, "gsea_kegg")

gobp_df <- run_gsea_go(gene_list, "BP")
save_gsea_result(gobp_df, output_dir, survival_name, "gsea_gobp")

gomf_df <- run_gsea_go(gene_list, "MF")
save_gsea_result(gomf_df, output_dir, survival_name, "gsea_gomf")

gocc_df <- run_gsea_go(gene_list, "CC")
save_gsea_result(gocc_df, output_dir, survival_name, "gsea_gocc")

message("Pipeline complete!")
