#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==============================================================================
#  Title: Analyze TCGA mRNA Expression
#  2026-06-29 | Shiwoo Koak | Seoul National University
#
#  Description:
#    Analyze TCGA mRNA expression between matched tumor and normal samples,
#    compare expression across normal, driver-mutant tumor, and driver-WT tumor
#    groups, and create gene-gene expression scatter plots. RNA-seq and SNV
#    inputs are generated by 01_download_tcga.R.
#
#  Usage:
#    python src/06_analyze_expression.py
#    Edit the user settings in main() or call the class directly from a notebook.
# ==============================================================================

################################################################################
# Step 0: Load Packages --------------------------------------------------------
################################################################################

import os
from itertools import combinations

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import gaussian_kde, kruskal, mannwhitneyu, pearsonr, t, wilcoxon
from statsmodels.stats.multitest import multipletests


################################################################################
# Step 1: Constants ------------------------------------------------------------
################################################################################

GREY = "#7F7F7F"
STEEL_BLUE = "#4682B4"
BRICK_RED = "#B22222"

DRIVER_STATUS_COLORS = {
    "Normal": GREY,
    "WT": STEEL_BLUE,
    "MT": BRICK_RED,
}

SAMPLE_TYPE_COLORS = {
    "Normal": GREY,
    "Tumor": BRICK_RED,
}


################################################################################
# Step 2: Utilities ------------------------------------------------------------
################################################################################

def format_pvalue(pvalue):
    if pd.isna(pvalue):
        return "NA"

    if pvalue < 0.001:
        return f"{pvalue:.2e}"

    return f"{pvalue:.3f}"


def format_group_label(group):
    if group.endswith(" WT") or group.endswith(" MT"):
        gene, status = group.rsplit(" ", 1)
        return rf"$\it{{{gene}}}$ {status}"

    return group


################################################################################
# Step 3: Analyze Expression ---------------------------------------------------
################################################################################

class AnalyzeExpression:
    """Analyze and visualize TCGA mRNA expression by sample group."""

    def __init__(self, expression_file, snv_file):
        self.expression_data = pd.read_csv(expression_file, sep="\t")
        self.snv_data = pd.read_csv(snv_file, sep="\t")

        self.expression_by_gene = (
            self.expression_data
            .drop_duplicates("gene_name", keep="first")
            .set_index("gene_name")
        )

        self.sample_columns = [
            column for column in self.expression_data.columns
            if str(column).startswith("TCGA-")
        ]
        self.tumor_samples = [
            sample for sample in self.sample_columns
            if sample[13:16] == "01A"
        ]
        self.normal_samples = [
            sample for sample in self.sample_columns
            if sample[13:16] == "11A"
        ]

        self.tumor_by_patient = {
            sample[:12]: sample for sample in self.tumor_samples
        }
        self.normal_by_patient = {
            sample[:12]: sample for sample in self.normal_samples
        }
        self.paired_patients = sorted(
            set(self.tumor_by_patient) & set(self.normal_by_patient)
        )

        print(f"Loaded genes: {self.expression_by_gene.shape[0]}")
        print(f"Tumor samples: {len(self.tumor_samples)}")
        print(f"Normal samples: {len(self.normal_samples)}")
        print(f"Matched tumor-normal pairs: {len(self.paired_patients)}")

    def get_expression(self, gene):
        """Return expression values for one gene across TCGA samples."""
        return pd.to_numeric(self.expression_by_gene.loc[gene, self.sample_columns])

    def get_mutant_samples(self, driver_gene):
        """Return primary tumor samples with an SNV in the driver gene."""
        driver_hits = self.snv_data[
            self.snv_data["gene_name"] == driver_gene
        ]

        return sorted(
            set(driver_hits["sample"]) & set(self.tumor_samples)
        )

    def compare_tumor_normal(self, gene, paired=False):
        """Compare gene expression between tumor and normal samples."""
        expression = self.get_expression(gene)

        if paired:
            comparison_data = self.create_paired_data(
                gene=gene,
                expression=expression,
            )
            paired_matrix = comparison_data.pivot(
                index="patient",
                columns="group",
                values="expression",
            )
            test_result = wilcoxon(
                paired_matrix["Tumor"],
                paired_matrix["Normal"],
                alternative="two-sided",
            )
            test_name = "Wilcoxon signed-rank"
            n_tumor = paired_matrix.shape[0]
            n_normal = paired_matrix.shape[0]
            median_difference = (
                paired_matrix["Tumor"] - paired_matrix["Normal"]
            ).median()
        else:
            comparison_data = pd.concat([
                self.create_group_data(
                    gene=gene,
                    expression=expression,
                    samples=self.normal_samples,
                    group="Normal",
                ),
                self.create_group_data(
                    gene=gene,
                    expression=expression,
                    samples=self.tumor_samples,
                    group="Tumor",
                ),
            ], ignore_index=True)
            normal_values = comparison_data.loc[
                comparison_data["group"] == "Normal",
                "expression",
            ]
            tumor_values = comparison_data.loc[
                comparison_data["group"] == "Tumor",
                "expression",
            ]
            test_result = mannwhitneyu(
                tumor_values,
                normal_values,
                alternative="two-sided",
            )
            test_name = "Mann-Whitney U"
            n_tumor = tumor_values.shape[0]
            n_normal = normal_values.shape[0]
            median_difference = tumor_values.median() - normal_values.median()

        tumor_expression = comparison_data.loc[
            comparison_data["group"] == "Tumor",
            "expression",
        ]
        normal_expression = comparison_data.loc[
            comparison_data["group"] == "Normal",
            "expression",
        ]

        stats_data = pd.DataFrame([{
            "gene_name": gene,
            "comparison": "paired" if paired else "unpaired",
            "test": test_name,
            "n_tumor": n_tumor,
            "n_normal": n_normal,
            "median_tumor": tumor_expression.median(),
            "median_normal": normal_expression.median(),
            "median_difference": median_difference,
            "statistic": test_result.statistic,
            "pvalue": test_result.pvalue,
        }])

        self.print_tumor_normal_stats(stats_data)

        return comparison_data, stats_data

    def plot_tumor_normal(
        self,
        comparison_data,
        stats_data,
        gene,
        output_path,
        paired=True,
    ):
        """Plot tumor-normal expression with boxplots and individual samples."""
        figsize = (2.5, 3.0)

        significance_data = pd.DataFrame([{
            "group1": "Normal",
            "group2": "Tumor",
            "pvalue": stats_data["pvalue"].iloc[0],
        }])

        self.plot_boxplot(
            plot_data=comparison_data,
            group_order=["Normal", "Tumor"],
            color_map=SAMPLE_TYPE_COLORS,
            y_label=rf"$\it{{{gene}}}$ log2(TPM + 1)",
            output_path=output_path,
            paired=paired,
            significance_data=significance_data,
            figsize=figsize,
        )

        print(f"Saved tumor-normal plot to: {output_path}")

    def compare_mutation_groups(self, gene, driver_gene):
        """Compare expression across normal, driver WT, and driver MT groups."""
        expression = self.get_expression(gene)
        mutant_samples = self.get_mutant_samples(driver_gene)
        wt_samples = sorted(set(self.tumor_samples) - set(mutant_samples))

        group_data = pd.concat([
            self.create_group_data(
                gene=gene,
                expression=expression,
                samples=self.normal_samples,
                group="Normal",
            ),
            self.create_group_data(
                gene=gene,
                expression=expression,
                samples=wt_samples,
                group=f"{driver_gene} WT",
            ),
            self.create_group_data(
                gene=gene,
                expression=expression,
                samples=mutant_samples,
                group=f"{driver_gene} MT",
            ),
        ], ignore_index=True)

        group_order = [
            "Normal",
            f"{driver_gene} WT",
            f"{driver_gene} MT",
        ]

        overall_test = kruskal(*[
            group_data.loc[group_data["group"] == group, "expression"]
            for group in group_order
        ])

        pairwise_results = []

        for group1, group2 in combinations(group_order, 2):
            values1 = group_data.loc[group_data["group"] == group1, "expression"]
            values2 = group_data.loc[group_data["group"] == group2, "expression"]
            test_result = mannwhitneyu(values1, values2, alternative="two-sided")

            pairwise_results.append({
                "gene_name": gene,
                "driver_gene": driver_gene,
                "comparison": f"{group1} vs {group2}",
                "test": "Mann-Whitney U",
                "n_group1": values1.shape[0],
                "n_group2": values2.shape[0],
                "median_group1": values1.median(),
                "median_group2": values2.median(),
                "statistic": test_result.statistic,
                "pvalue": test_result.pvalue,
            })

        stats_data = pd.DataFrame(pairwise_results)
        stats_data["FDR"] = multipletests(stats_data["pvalue"], method="fdr_bh")[1]

        overall_data = pd.DataFrame([{
            "gene_name": gene,
            "driver_gene": driver_gene,
            "comparison": "overall",
            "test": "Kruskal-Wallis",
            "n_group1": np.nan,
            "n_group2": np.nan,
            "median_group1": np.nan,
            "median_group2": np.nan,
            "statistic": overall_test.statistic,
            "pvalue": overall_test.pvalue,
            "FDR": np.nan,
        }])

        all_stats = pd.concat([overall_data, stats_data], ignore_index=True)
        self.print_mutation_group_stats(all_stats)

        return group_data, all_stats

    def plot_mutation_groups(
        self,
        group_data,
        stats_data,
        gene,
        driver_gene,
        output_path,
    ):
        """Plot expression grouped by driver mutation status."""
        figsize = (3.2, 3.0)

        group_order = [
            "Normal",
            f"{driver_gene} WT",
            f"{driver_gene} MT",
        ]
        color_map = {
            "Normal": DRIVER_STATUS_COLORS["Normal"],
            f"{driver_gene} WT": DRIVER_STATUS_COLORS["WT"],
            f"{driver_gene} MT": DRIVER_STATUS_COLORS["MT"],
        }
        pairwise_stats = stats_data[stats_data["comparison"] != "overall"].copy()

        # The plot labels use FDR-adjusted p values from pairwise tests.
        significance_data = pd.DataFrame([
            {
                "group1": comparison.split(" vs ")[0],
                "group2": comparison.split(" vs ")[1],
                "pvalue": fdr_value,
            }
            for comparison, fdr_value in zip(
                pairwise_stats["comparison"],
                pairwise_stats["FDR"],
            )
        ])

        self.plot_boxplot(
            plot_data=group_data,
            group_order=group_order,
            color_map=color_map,
            y_label=rf"$\it{{{gene}}}$ log2(TPM + 1)",
            output_path=output_path,
            paired=False,
            significance_data=significance_data,
            figsize=figsize,
        )

        print(f"Saved mutation-group plot to: {output_path}")

    def plot_scatter(
        self,
        x_gene,
        y_gene,
        output_path,
        plot_normal=True,
        driver_gene=None,
    ):
        """Plot the expression relationship between two genes."""
        x_expression = self.get_expression(x_gene)
        y_expression = self.get_expression(y_gene)

        scatter_data = self.create_scatter_data(
            x_expression=x_expression,
            y_expression=y_expression,
            x_gene=x_gene,
            y_gene=y_gene,
            plot_normal=plot_normal,
            driver_gene=driver_gene,
        )

        if driver_gene is None:
            plot_order = ["Tumor"]
            legend_order = ["Tumor"]

            if plot_normal:
                plot_order = ["Normal"] + plot_order
                legend_order = legend_order + ["Normal"]

            color_map = SAMPLE_TYPE_COLORS
        else:
            plot_order = [
                f"{driver_gene} WT",
                f"{driver_gene} MT",
            ]
            legend_order = [
                f"{driver_gene} MT",
                f"{driver_gene} WT",
            ]

            if plot_normal:
                plot_order = ["Normal"] + plot_order
                legend_order = legend_order + ["Normal"]

            color_map = {
                "Normal": DRIVER_STATUS_COLORS["Normal"],
                f"{driver_gene} WT": DRIVER_STATUS_COLORS["WT"],
                f"{driver_gene} MT": DRIVER_STATUS_COLORS["MT"],
            }

        figsize = (4.2, 3)

        fig, (ax, legend_ax) = plt.subplots(
            ncols=2,
            figsize=figsize,
            constrained_layout=True,
            gridspec_kw={
                "width_ratios": [2, 1],
                "wspace": 0.08,
            },
        )

        for group in plot_order:
            group_data = scatter_data[scatter_data["group"] == group]

            ax.scatter(
                group_data["x_expression"],
                group_data["y_expression"],
                s=22,
                alpha=0.80,
                color=color_map[group],
                edgecolor="none",
            )

        self.add_regression_line(ax, scatter_data)
        self.add_scatter_legend(legend_ax, legend_order, color_map)

        ax.set_xlabel(rf"$\it{{{x_gene}}}$ log2(TPM + 1)")
        ax.set_ylabel(rf"$\it{{{y_gene}}}$ log2(TPM + 1)")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(axis="both", labelsize=9)

        fig.savefig(output_path, format="svg", bbox_inches="tight")
        plt.close(fig)

        print(f"Saved scatter plot to: {output_path}")

        return scatter_data

    def create_paired_data(self, gene, expression):
        """Create long-format expression data for matched tumor-normal pairs."""
        comparison_data = []

        for patient in self.paired_patients:
            normal_sample = self.normal_by_patient[patient]
            tumor_sample = self.tumor_by_patient[patient]

            comparison_data.append({
                "sample": normal_sample,
                "patient": patient,
                "gene_name": gene,
                "group": "Normal",
                "expression": expression[normal_sample],
            })
            comparison_data.append({
                "sample": tumor_sample,
                "patient": patient,
                "gene_name": gene,
                "group": "Tumor",
                "expression": expression[tumor_sample],
            })

        return pd.DataFrame(comparison_data)

    def create_group_data(self, gene, expression, samples, group):
        """Create long-format expression data for one sample group."""
        return pd.DataFrame({
            "sample": samples,
            "patient": [sample[:12] for sample in samples],
            "gene_name": gene,
            "group": group,
            "expression": [expression[sample] for sample in samples],
        })

    def print_tumor_normal_stats(self, stats_data):
        """Print tumor-normal comparison statistics."""
        stats = stats_data.iloc[0]

        print("Tumor-normal comparison")
        print(f"  - Gene: {stats['gene_name']}")
        print(f"  - Test: {stats['test']}")
        print(f"  - Tumor samples: {stats['n_tumor']}")
        print(f"  - Normal samples: {stats['n_normal']}")
        print(f"  - Median tumor: {stats['median_tumor']:.3f}")
        print(f"  - Median normal: {stats['median_normal']:.3f}")
        print(f"  - Median difference: {stats['median_difference']:.3f}")
        print(f"  - P: {format_pvalue(stats['pvalue'])}")

    def print_mutation_group_stats(self, stats_data):
        """Print mutation-group comparison statistics."""
        overall_stats = stats_data[stats_data["comparison"] == "overall"].iloc[0]
        pairwise_stats = stats_data[stats_data["comparison"] != "overall"]

        print("Mutation-group comparison")
        print(f"  - Gene: {overall_stats['gene_name']}")
        print(f"  - Driver gene: {overall_stats['driver_gene']}")
        print(f"  - Overall test: {overall_stats['test']}")
        print(f"  - Overall P: {format_pvalue(overall_stats['pvalue'])}")
        print("  - Pairwise tests:")

        for _, row in pairwise_stats.iterrows():
            print(
                f"    {row['comparison']}: "
                f"P = {format_pvalue(row['pvalue'])}, "
                f"FDR = {format_pvalue(row['FDR'])}"
            )

    def plot_boxplot(
        self,
        plot_data,
        group_order,
        color_map,
        y_label,
        output_path,
        paired=False,
        significance_data=None,
        figsize=None,
    ):
        """Plot boxplots with density-spread dots and optional p-value bars."""
        fig, ax = plt.subplots(figsize=figsize)
        x_positions = np.arange(1, len(group_order) + 1)
        rng = np.random.default_rng(1)

        box_values = [
            plot_data.loc[plot_data["group"] == group, "expression"]
            for group in group_order
        ]

        boxplot = ax.boxplot(
            box_values,
            positions=x_positions,
            widths=0.48,
            patch_artist=True,
            showfliers=False,
        )

        for patch, group in zip(boxplot["boxes"], group_order):
            patch.set_facecolor(color_map[group])
            patch.set_alpha(0.35)
            patch.set_edgecolor("black")

        for element in ["whiskers", "caps", "medians"]:
            for line in boxplot[element]:
                line.set_color("black")
                line.set_linewidth(1.0)

        point_positions = {}

        for x, group in zip(x_positions, group_order):
            group_data = plot_data[plot_data["group"] == group].copy()
            group_values = group_data["expression"].to_numpy(float)
            jitter = self.get_violin_jitter(group_values, rng)

            # Store jittered x positions so paired lines hit the actual dots.
            point_positions[group] = pd.DataFrame({
                "patient": group_data["patient"].to_numpy(),
                "x": np.repeat(x, group_values.shape[0]) + jitter,
                "expression": group_values,
            })

        if paired:
            paired_points = point_positions[group_order[0]].merge(
                point_positions[group_order[1]],
                on="patient",
                suffixes=("_1", "_2"),
            )

            for _, row in paired_points.iterrows():
                ax.plot(
                    [row["x_1"], row["x_2"]],
                    [row["expression_1"], row["expression_2"]],
                    color="#B0B0B0",
                    lw=0.6,
                    alpha=0.60,
                    zorder=1,
                )

        for group in group_order:
            group_points = point_positions[group]

            ax.scatter(
                group_points["x"],
                group_points["expression"],
                s=15,
                alpha=0.55,
                color=color_map[group],
                edgecolor="#333333",
                linewidth=0.25,
                zorder=2,
            )

        self.add_pvalue_bars(
            ax=ax,
            plot_data=plot_data,
            group_order=group_order,
            significance_data=significance_data,
        )

        ax.set_xticks(x_positions)
        ax.set_xticklabels(
            [format_group_label(group) for group in group_order],
            fontsize=9,
        )
        ax.set_ylabel(y_label)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.tick_params(axis="y", labelsize=9)

        fig.tight_layout()
        fig.savefig(output_path, format="svg", bbox_inches="tight")
        plt.close(fig)

    def get_violin_jitter(self, values, rng, max_width=0.25):
        """Create density-scaled jitter for a violin-like dot layout."""
        if len(values) < 3 or np.std(values) == 0:
            return rng.uniform(-0.04, 0.04, size=len(values))

        # Dense y-regions get wider horizontal spread; sparse regions stay tight.
        density = gaussian_kde(values)(values)
        density = density / density.max()
        jitter_width = max_width * density

        return rng.uniform(-jitter_width, jitter_width)

    def add_pvalue_bars(
        self,
        ax,
        plot_data,
        group_order,
        significance_data,
    ):
        """Add p-value brackets above boxplot groups."""
        if significance_data is None or significance_data.empty:
            return

        group_position = {
            group: i + 1
            for i, group in enumerate(group_order)
        }
        y_min = plot_data["expression"].min()
        y_max = plot_data["expression"].max()
        y_range = max(y_max - y_min, 1.0)
        y_start = y_max + 0.08 * y_range
        y_step = 0.10 * y_range
        tick_height = 0.025 * y_range

        for i, (_, row) in enumerate(significance_data.iterrows()):
            group1 = row["group1"]
            group2 = row["group2"]

            if group1 not in group_position or group2 not in group_position:
                continue

            x1 = group_position[group1]
            x2 = group_position[group2]
            y = y_start + i * y_step

            ax.plot(
                [x1, x1, x2, x2],
                [y, y + tick_height, y + tick_height, y],
                color="black",
                lw=0.8,
            )
            pvalue_label = rf"$\it{{P}}$ = {format_pvalue(row['pvalue'])}"

            ax.text(
                (x1 + x2) / 2,
                y + tick_height,
                pvalue_label,
                ha="center",
                va="bottom",
                fontsize=9,
            )

        ax.set_ylim(top=y_start + len(significance_data) * y_step)

    def add_scatter_legend(self, ax, group_order, color_map):
        """Draw a compact dot legend on a separate axis."""
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")

        legend_spacing = 0.07
        legend_center = 0.50
        y_positions = (
            legend_center +
            legend_spacing * (len(group_order) - 1) / 2 -
            legend_spacing * np.arange(len(group_order))
        )

        for y, group in zip(y_positions, group_order):
            ax.scatter(
                0.15,
                y,
                s=28,
                alpha=0.80,
                color=color_map[group],
                edgecolor="none",
            )
            ax.text(
                0.28,
                y,
                format_group_label(group),
                ha="left",
                va="center",
                fontsize=9,
            )

    def add_regression_line(self, ax, scatter_data):
        """Add Pearson correlation, regression line, and 95% CI."""
        x = scatter_data["x_expression"].to_numpy(float)
        y = scatter_data["y_expression"].to_numpy(float)
        finite = np.isfinite(x) & np.isfinite(y)
        x = x[finite]
        y = y[finite]

        r_value, p_value = pearsonr(x, y)
        slope, intercept = np.polyfit(x, y, deg=1)

        x_grid = np.linspace(x.min(), x.max(), 200)
        y_fit = intercept + slope * x_grid

        # Confidence interval for the mean fitted regression line.
        residuals = y - (intercept + slope * x)
        residual_se = np.sqrt(np.sum(residuals ** 2) / (len(x) - 2))
        x_mean = np.mean(x)
        x_ss = np.sum((x - x_mean) ** 2)
        ci = (
            t.ppf(0.975, df=len(x) - 2) *
            residual_se *
            np.sqrt(1 / len(x) + (x_grid - x_mean) ** 2 / x_ss)
        )

        ax.plot(
            x_grid,
            y_fit,
            color="black",
            lw=1.1,
            zorder=3,
        )
        ax.fill_between(
            x_grid,
            y_fit - ci,
            y_fit + ci,
            color="black",
            alpha=0.12,
            linewidth=0,
            zorder=0,
        )
        correlation_label = (
            f"R = {r_value:.2f}"
            "\n"
            rf"$\it{{P}}$ = {format_pvalue(p_value)}"
        )

        ax.text(
            0.05,
            0.95,
            correlation_label,
            transform=ax.transAxes,
            ha="left",
            va="top",
            fontsize=9,
        )

    def create_scatter_data(
        self,
        x_expression,
        y_expression,
        x_gene,
        y_gene,
        plot_normal,
        driver_gene,
    ):
        """Create long-format x/y expression data for scatter plots."""
        if driver_gene is None:
            sample_groups = {
                "Tumor": self.tumor_samples,
            }
        else:
            mutant_samples = self.get_mutant_samples(driver_gene)
            wt_samples = sorted(set(self.tumor_samples) - set(mutant_samples))
            sample_groups = {
                f"{driver_gene} WT": wt_samples,
                f"{driver_gene} MT": mutant_samples,
            }

        if plot_normal:
            sample_groups = {
                "Normal": self.normal_samples,
                **sample_groups,
            }

        scatter_data = []

        for group, samples in sample_groups.items():
            for sample in samples:
                scatter_data.append({
                    "sample": sample,
                    "patient": sample[:12],
                    "group": group,
                    "x_gene": x_gene,
                    "y_gene": y_gene,
                    "x_expression": x_expression[sample],
                    "y_expression": y_expression[sample],
                })

        return pd.DataFrame(scatter_data)


################################################################################
# Step 4: Main -----------------------------------------------------------------
################################################################################

def main():
    # ---- User settings --------------------------------------------------------
    cancer_type = "LIHC"
    data_dir = "data"
    output_dir = data_dir

    exp_file = os.path.join(
        data_dir,
        f"TCGA_{cancer_type}",
        f"{cancer_type}_rnaseq_log2tpm.tsv",
    )
    snv_file = os.path.join(
        data_dir,
        f"TCGA_{cancer_type}",
        f"{cancer_type}_snv.tsv",
    )
    os.makedirs(output_dir, exist_ok=True)

    # 1) Initialize analysis
    analysis = AnalyzeExpression(
        expression_file=exp_file,
        snv_file=snv_file,
    )

    # 2) Compare tumor and normal expression
    expression_gene = "RBM39"
    paired = True
    comparison = "paired" if paired else "unpaired"

    tumor_normal_data, tumor_normal_stats = (
        analysis.compare_tumor_normal(gene=expression_gene, paired=paired)
    )
    tumor_normal_stats_file = os.path.join(
        output_dir,
        f"{cancer_type}_{expression_gene}_{comparison}_tumor_normal_stats.tsv",
    )
    tumor_normal_stats.to_csv(
        tumor_normal_stats_file,
        sep="\t",
        index=False,
    )

    tumor_normal_plot_file = os.path.join(
        output_dir,
        f"{cancer_type}_{expression_gene}_{comparison}_tumor_normal_box.svg",
    )
    analysis.plot_tumor_normal(
        comparison_data=tumor_normal_data,
        stats_data=tumor_normal_stats,
        gene=expression_gene,
        output_path=tumor_normal_plot_file,
        paired=paired,
    )

    # 3) Compare expression by driver mutation status
    expression_gene = "RBM39"
    driver_gene = "CTNNB1"

    group_data, group_stats = analysis.compare_mutation_groups(
        gene=expression_gene,
        driver_gene=driver_gene,
    )
    group_stats_file = os.path.join(
        output_dir,
        f"{cancer_type}_{expression_gene}_{driver_gene}_mutation_group_stats.tsv",
    )
    group_stats.to_csv(
        group_stats_file,
        sep="\t",
        index=False,
    )

    group_plot_file = os.path.join(
        output_dir,
        f"{cancer_type}_{expression_gene}_{driver_gene}_mutation_group_box.svg",
    )
    analysis.plot_mutation_groups(
        group_data=group_data,
        stats_data=group_stats,
        gene=expression_gene,
        driver_gene=driver_gene,
        output_path=group_plot_file,
    )

    # 4) Plot gene-gene expression scatter plots
    scatter_x_gene = "CPS1"
    scatter_y_gene = "RBM39"
    plot_normal = True

    sample_type_scatter_file = os.path.join(
        output_dir,
        f"{cancer_type}_{scatter_x_gene}_{scatter_y_gene}_scatter_sample_type.svg",
    )
    analysis.plot_scatter(
        x_gene=scatter_x_gene,
        y_gene=scatter_y_gene,
        output_path=sample_type_scatter_file,
        plot_normal=plot_normal,
    )

    scatter_x_gene = "CPS1"
    scatter_y_gene = "RBM39"
    driver_gene = "CTNNB1"
    plot_normal = True

    driver_scatter_file = os.path.join(
        output_dir,
        f"{cancer_type}_{scatter_x_gene}_{scatter_y_gene}_{driver_gene}_scatter.svg",
    )
    analysis.plot_scatter(
        x_gene=scatter_x_gene,
        y_gene=scatter_y_gene,
        output_path=driver_scatter_file,
        plot_normal=plot_normal,
        driver_gene=driver_gene,
    )


if __name__ == "__main__":
    main()
