#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# ==============================================================================
#  Title: Create TCGA Oncoprint
#  2026-06-25 | Shiwoo Koak | Seoul National University
#
#  Description:
#    Create an oncoprint using TCGA somatic mutation and copy-number data
#    generated by 01_download_tcga.R. The script builds a gene-by-sample
#    alteration matrix from primary tumor (-01A) SNV and deep CNV events,
#    tests pairwise gene co-occurrence with Fisher's exact test, and saves a
#    publication-ready SVG.
#
#  Usage:
#    python src/07_oncoprint.py <cancer> <gene1> [gene2 ...]
#
#  Output:
#    data/<cancer>_oncoprint_fisher.tsv
#    data/<cancer>_oncoprint_fisher_heatmap.svg
#    data/<cancer>_oncoprint.svg
# ==============================================================================

################################################################################
# Step 0: Load Packages --------------------------------------------------------
################################################################################

import argparse
import os

import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.gridspec import GridSpecFromSubplotSpec
from matplotlib.transforms import blended_transform_factory
from scipy.cluster.hierarchy import leaves_list, linkage
from scipy.spatial.distance import pdist
from scipy.stats import fisher_exact
from statsmodels.stats.multitest import multipletests


################################################################################
# Step 1: Constants ------------------------------------------------------------
################################################################################

ALTERATION_COLORS = {
    "Amplification": "#B22222",
    "Deletion": "#4169E1",
    "Frame_Shift": "#FADADD",
    "In_Frame_Indel": "#9E9AC8",
    "Missense_Mutation": "#6FB1DC",
    "Nonsense_Mutation": "#FDAE6B",
    "Splice_Site": "#FDD670",
    "Other": "#BDBDBD",
}

VARIANT_LABEL_MAP = {
    "Frame_Shift_Ins": "Frame_Shift",
    "Frame_Shift_Del": "Frame_Shift",
    "In_Frame_Ins": "In_Frame_Indel",
    "In_Frame_Del": "In_Frame_Indel",
}


################################################################################
# Step 2: Utilities ------------------------------------------------------------
################################################################################

def append_alteration(current_alterations, new_alteration):
    if not new_alteration:
        return current_alterations

    if pd.isna(current_alterations) or current_alterations == "":
        return new_alteration

    alterations = [
        x.strip() for x in str(current_alterations).split(",")
        if x.strip()
    ]

    if new_alteration not in alterations:
        alterations.append(new_alteration)

    return ",".join(alterations)


def collapse_alterations(cell):
    if pd.isna(cell) or cell == "":
        return ""

    alterations = {
        VARIANT_LABEL_MAP.get(alteration.strip(), alteration.strip())
        for alteration in str(cell).split(",")
        if alteration.strip()
    }

    return ",".join(sorted(alterations))


def parse_alterations(cell):
    if pd.isna(cell) or cell == "":
        return []

    raw_alterations = [
        VARIANT_LABEL_MAP.get(alteration.strip(), alteration.strip())
        for alteration in str(cell).split(",")
        if alteration.strip()
    ]

    known_alterations = {
        alteration for alteration in raw_alterations
        if alteration in ALTERATION_COLORS
    }
    unknown_alterations = [
        alteration for alteration in raw_alterations
        if alteration not in ALTERATION_COLORS
    ]

    if unknown_alterations:
        known_alterations.add("Other")

    return [
        alteration for alteration in ALTERATION_COLORS
        if alteration in known_alterations
    ]


def get_heatmap_figure_size(n_genes):
    side = max(4.5, min(10.0, 0.45 * n_genes + 3.0))
    return side, side


def get_fdr_star(fdr_value):
    if pd.isna(fdr_value):
        return ""

    if fdr_value < 0.001:
        return "***"

    if fdr_value < 0.01:
        return "**"

    if fdr_value < 0.05:
        return "*"

    return ""


def get_cluster_order(matrix):
    distance = pdist(matrix, metric="euclidean")
    return leaves_list(linkage(distance, method="average"))


################################################################################
# Step 3: Build Alteration Matrix ----------------------------------------------
################################################################################

class OncoprintAnalysis:

    def __init__(self, snv_file, cnv_file, genes):
        self.snv_data = pd.read_csv(snv_file, sep="\t")
        self.cnv_data = pd.read_csv(cnv_file, sep="\t")
        self.genes = genes

        self.samples = [
            column for column in self.cnv_data.columns
            if len(str(column)) == 16 and str(column)[13:16] == "01A"
        ]

        self.cnv_by_gene = (
            self.cnv_data[self.cnv_data["gene_name"].isin(self.genes)]
            .drop_duplicates("gene_name", keep="first")
            .set_index("gene_name")
        )
        self.alteration_matrix = pd.DataFrame(
            "",
            index=self.genes,
            columns=self.samples,
        )

        print(f"Loaded genes: {len(self.genes)}")
        print(f"Primary tumor samples: {len(self.samples)}")

    def add_snv_data(self):
        snv_hits = self.snv_data[
            self.snv_data["gene_name"].isin(self.genes) &
            self.snv_data["sample"].isin(self.samples)
        ].copy()

        snv_alterations = (
            snv_hits
            .assign(
                alteration=lambda x: x["variant_classification"].astype(str).str.strip()
            )
            .query("alteration != ''")
            .groupby(["gene_name", "sample"])["alteration"]
            .apply(lambda x: ",".join(sorted(set(x))))
        )

        for (gene, sample), alterations in snv_alterations.items():
            current_alterations = self.alteration_matrix.at[gene, sample]
            self.alteration_matrix.at[gene, sample] = append_alteration(
                current_alterations,
                alterations,
            )

        print(f"  - SNV events added: {len(snv_alterations)}")

    def add_cnv_data(self):
        n_cnv_events = 0

        for gene in self.genes:
            if gene not in self.cnv_by_gene.index:
                continue

            cnv_values = pd.to_numeric(
                self.cnv_by_gene.loc[gene].reindex(self.samples),
                errors="coerce",
            )

            for sample in cnv_values.index[cnv_values == 2]:
                current_alterations = self.alteration_matrix.at[gene, sample]
                self.alteration_matrix.at[gene, sample] = append_alteration(
                    current_alterations,
                    "Amplification",
                )
                n_cnv_events += 1

            for sample in cnv_values.index[cnv_values == -2]:
                current_alterations = self.alteration_matrix.at[gene, sample]
                self.alteration_matrix.at[gene, sample] = append_alteration(
                    current_alterations,
                    "Deletion",
                )
                n_cnv_events += 1

        print(f"  - CNV events added: {n_cnv_events}")

    def refine_matrix(self):
        self.alteration_matrix = self.alteration_matrix.apply(
            lambda column: column.map(collapse_alterations)
        )

        alteration_counts = (self.alteration_matrix != "").sum(axis=1)
        gene_order = alteration_counts.sort_values(ascending=False).index
        self.alteration_matrix = self.alteration_matrix.loc[gene_order]

        binary_matrix = (self.alteration_matrix != "").astype(int)
        sample_patterns = binary_matrix.T.apply(
            lambda row: "".join(row.astype(str)),
            axis=1,
        )

        sample_order = (
            sample_patterns
            .to_frame("pattern")
            .assign(sample=sample_patterns.index)
            .sort_values(["pattern", "sample"], ascending=[False, True])
            .index
        )

        self.alteration_matrix = self.alteration_matrix.loc[:, sample_order]

    def run_fisher_test(self, output_path):
        binary_matrix = (self.alteration_matrix != "").astype(int)
        genes = binary_matrix.index.tolist()
        fisher_results = []

        for i, gene1 in enumerate(genes):
            for gene2 in genes[i + 1:]:
                gene1_status = binary_matrix.loc[gene1] == 1
                gene2_status = binary_matrix.loc[gene2] == 1

                both_altered = int((gene1_status & gene2_status).sum())
                gene1_only = int((gene1_status & ~gene2_status).sum())
                gene2_only = int((~gene1_status & gene2_status).sum())
                neither_altered = int((~gene1_status & ~gene2_status).sum())

                contingency_table = np.array([
                    [both_altered, gene1_only],
                    [gene2_only, neither_altered],
                ])

                if (
                    (contingency_table.sum(axis=0) == 0).any() or
                    (contingency_table.sum(axis=1) == 0).any()
                ):
                    continue

                odds_ratio, p_value = fisher_exact(
                    contingency_table,
                    alternative="two-sided",
                )

                fisher_results.append({
                    "gene1": gene1,
                    "gene2": gene2,
                    "odds_ratio": odds_ratio,
                    "n_both_altered": both_altered,
                    "n_gene1_only": gene1_only,
                    "n_gene2_only": gene2_only,
                    "n_neither_altered": neither_altered,
                    "pvalue": p_value,
                })

        fisher_data = pd.DataFrame(fisher_results)

        if fisher_data.empty:
            fisher_data = pd.DataFrame(columns=[
                "gene1",
                "gene2",
                "odds_ratio",
                "n_both_altered",
                "n_gene1_only",
                "n_gene2_only",
                "n_neither_altered",
                "pvalue",
                "FDR",
            ])
        else:
            fisher_data["FDR"] = multipletests(
                fisher_data["pvalue"],
                method="fdr_bh",
            )[1]

        fisher_data.to_csv(output_path, sep="\t", index=False)
        print(f"Saved Fisher test results to: {output_path}")

        return fisher_data

    def plot_fisher_heatmap(self, fisher_data, output_path):
        genes = self.alteration_matrix.index.tolist()
        n_genes = len(genes)

        gene_index = {gene: i for i, gene in enumerate(genes)}
        heatmap_data = np.full((n_genes, n_genes), np.nan, dtype=float)
        fdr_data = np.full((n_genes, n_genes), np.nan, dtype=float)
        np.fill_diagonal(heatmap_data, 0.0)
        np.fill_diagonal(fdr_data, np.nan)

        for _, row in fisher_data.iterrows():
            gene1 = row["gene1"]
            gene2 = row["gene2"]
            odds_ratio = row["odds_ratio"]
            fdr_value = row["FDR"]

            if odds_ratio == 0:
                log2_or = -np.inf
            else:
                log2_or = np.log2(odds_ratio)

            i = gene_index[gene1]
            j = gene_index[gene2]

            heatmap_data[i, j] = log2_or
            heatmap_data[j, i] = log2_or
            fdr_data[i, j] = fdr_value
            fdr_data[j, i] = fdr_value

        off_diagonal = ~np.eye(n_genes, dtype=bool)
        finite_values = heatmap_data[off_diagonal & np.isfinite(heatmap_data)]
        finite_values = finite_values[finite_values != 0]

        if finite_values.size == 0:
            vmax = 1.0
        else:
            vmax = float(np.nanmax(np.abs(finite_values)))
            vmax = max(vmax, 1.0)

        heatmap_data = np.clip(heatmap_data, -vmax, vmax)
        np.fill_diagonal(heatmap_data, vmax)

        cluster_data = np.nan_to_num(
            heatmap_data,
            nan=0.0,
            posinf=vmax,
            neginf=-vmax,
        )
        order = get_cluster_order(cluster_data)

        heatmap_data = heatmap_data[np.ix_(order, order)]
        fdr_data = fdr_data[np.ix_(order, order)]
        genes = [genes[i] for i in order]

        cmap = plt.get_cmap("RdBu_r").copy()
        cmap.set_bad("#F2F2F2")

        fig, ax = plt.subplots(figsize=get_heatmap_figure_size(n_genes))
        image = ax.imshow(
            heatmap_data,
            cmap=cmap,
            vmin=-vmax,
            vmax=vmax,
            interpolation="nearest",
        )

        ax.set_xticks(np.arange(n_genes))
        ax.set_yticks(np.arange(n_genes))
        ax.set_xticklabels(genes, rotation=45, ha="right", fontstyle="italic")
        ax.set_yticklabels(genes, fontstyle="italic")

        for i in range(n_genes):
            for j in range(n_genes):
                if i == j:
                    continue

                star_label = get_fdr_star(fdr_data[i, j])

                if star_label:
                    value = heatmap_data[i, j]
                    text_color = (
                        "white"
                        if np.isfinite(value) and abs(value) > 0.65 * vmax
                        else "black"
                    )

                    ax.text(
                        j,
                        i,
                        star_label,
                        ha="center",
                        va="center",
                        color=text_color,
                        fontsize=10,
                        fontweight="bold",
                    )

        fig.subplots_adjust(left=0.22, right=0.80, bottom=0.22, top=0.98)

        ax_position = ax.get_position()
        colorbar_host = fig.add_axes([
            ax_position.x1 + 0.04,
            ax_position.y0,
            0.12,
            ax_position.height,
        ])
        colorbar_host.axis("off")

        colorbar_height = min(1.5, n_genes) / n_genes
        colorbar_y = (1.0 - colorbar_height) / 2.0
        colorbar_axis = colorbar_host.inset_axes([
            0.15,
            colorbar_y,
            0.20,
            colorbar_height,
        ])

        colorbar = fig.colorbar(image, cax=colorbar_axis)
        colorbar.ax.tick_params(labelsize=8, length=3)

        if colorbar.solids is not None:
            colorbar.solids.set_edgecolor("face")
            colorbar.solids.set_linewidth(0)

        colorbar.ax.set_xlabel(
            "log2(OR)",
            fontsize=9,
            labelpad=6,
        )

        fig.savefig(output_path, format="svg", bbox_inches="tight")
        plt.close(fig)

        print(f"Saved Fisher heatmap to: {output_path}")

    def plot_oncoprint(self, output_path):
        alteration_matrix = self.alteration_matrix.copy()
        genes = alteration_matrix.index.tolist()
        samples = alteration_matrix.columns.tolist()

        n_genes = len(genes)
        n_samples = len(samples)

        plt.rcParams.update({"font.size": 10})

        legend_height = 0.50
        middle_height = max(2.5, 0.20 * n_genes)

        fig = plt.figure(figsize=(8.0, middle_height + legend_height))
        outer_grid = fig.add_gridspec(
            2,
            1,
            height_ratios=[middle_height, legend_height],
            left=0.06,
            right=0.98,
            top=0.98,
            bottom=0.06,
            hspace=0.0,
        )

        middle_grid = GridSpecFromSubplotSpec(
            1,
            2,
            subplot_spec=outer_grid[0],
            width_ratios=[7, 1],
            wspace=0.02,
        )

        ax_heatmap = fig.add_subplot(middle_grid[0, 0])
        ax_heatmap.axis("off")

        ax_bar = fig.add_subplot(middle_grid[0, 1], sharey=ax_heatmap)

        heatmap_position = ax_heatmap.get_position()

        ax_heatmap.set_xlim(-0.5, n_samples - 0.5)
        ax_heatmap.set_ylim(n_genes - 0.5, -0.5)

        text_transform = blended_transform_factory(
            ax_heatmap.transAxes,
            ax_heatmap.transData,
        )

        for i, gene in enumerate(genes):
            for j, sample in enumerate(samples):
                alterations = parse_alterations(alteration_matrix.at[gene, sample])

                if not alterations:
                    continue

                alteration_height = 1.0 / len(alterations)

                for k, alteration in enumerate(alterations):
                    ax_heatmap.add_patch(
                        mpatches.Rectangle(
                            (j - 0.5, i - 0.5 + k * alteration_height),
                            1,
                            alteration_height,
                            facecolor=ALTERATION_COLORS[alteration],
                            edgecolor="white",
                            lw=0.25,
                        )
                    )

        for y in np.arange(0.5, n_genes - 0.5):
            ax_heatmap.axhline(y, color="gray", lw=0.35)

        for i, gene in enumerate(genes):
            percent_altered = (
                (alteration_matrix.loc[gene] != "").sum() /
                float(n_samples) * 100.0
            )

            ax_heatmap.text(
                -0.01,
                i,
                rf"$\it{{{gene}}}$ ({percent_altered:.0f}%)",
                transform=text_transform,
                ha="right",
                va="center",
                fontsize=9,
            )

        ax_heatmap.add_patch(
            mpatches.Rectangle(
                (-0.5, -0.5),
                n_samples,
                n_genes,
                edgecolor="black",
                facecolor="none",
                lw=2,
            )
        )

        alteration_summary = pd.DataFrame(
            0,
            index=genes,
            columns=list(ALTERATION_COLORS),
        )

        for gene in genes:
            for cell in alteration_matrix.loc[gene]:
                for alteration in parse_alterations(cell):
                    alteration_summary.at[gene, alteration] += 1

        y_positions = np.arange(n_genes)
        bar_left = np.zeros(n_genes)

        for alteration, color in ALTERATION_COLORS.items():
            values = alteration_summary[alteration].values

            ax_bar.barh(
                y_positions,
                values,
                color=color,
                height=0.8,
                left=bar_left,
                edgecolor="none",
            )

            bar_left += values

        ax_bar.set_xlabel("# Alterations", fontsize=9)
        ax_bar.set_xlim(0, max(1, bar_left.max()) * 1.1)
        ax_bar.set_yticks([])
        ax_bar.spines["top"].set_visible(False)
        ax_bar.spines["right"].set_visible(False)
        ax_bar.tick_params(axis="x", labelsize=8)

        ax_legend = fig.add_subplot(outer_grid[1])
        ax_legend.axis("off")

        legend_position = ax_legend.get_position()
        ax_legend.set_position([
            heatmap_position.x0,
            legend_position.y0,
            heatmap_position.width,
            legend_position.height,
        ])

        legend_order = [
            "Missense_Mutation",
            "Amplification",
            "Nonsense_Mutation",
            "Deletion",
            "In_Frame_Indel",
            "Splice_Site",
            "Frame_Shift",
            "Other",
        ]

        handles = [
            mpatches.Patch(color=ALTERATION_COLORS[alteration], label=alteration)
            for alteration in legend_order
        ]

        legend = ax_legend.legend(
            handles=handles,
            loc="center",
            ncol=4,
            frameon=False,
            handlelength=1.2,
            columnspacing=1.1,
            labelspacing=0.6,
            fontsize=8,
        )

        for handle in legend.legend_handles:
            handle.set_linewidth(0)

        fig.savefig(output_path, format="svg", bbox_inches="tight")
        plt.close(fig)

        print(f"Saved oncoprint to: {output_path}")


################################################################################
# Step 4: Main -----------------------------------------------------------------
################################################################################

def main():
    parser = argparse.ArgumentParser(
        description="Create a TCGA SNV/CNV oncoprint.",
    )
    parser.add_argument(
        "cancer",
        help="TCGA cancer type abbreviation, for example LIHC or LUAD.",
    )
    parser.add_argument(
        "genes",
        nargs="+",
        help="Gene symbols to include in the oncoprint.",
    )
    args = parser.parse_args()
    cancer = args.cancer.upper()
    data_dir = "data"
    genes = args.genes

    snv_path = os.path.join(
        data_dir,
        f"TCGA_{cancer}",
        f"{cancer}_snv.tsv",
    )
    cnv_path = os.path.join(
        data_dir,
        f"TCGA_{cancer}",
        f"{cancer}_cnv.tsv",
    )
    fisher_path = os.path.join(
        data_dir,
        f"{cancer}_oncoprint_fisher.tsv",
    )
    heatmap_path = os.path.join(
        data_dir,
        f"{cancer}_oncoprint_fisher_heatmap.svg",
    )
    oncoprint_path = os.path.join(
        data_dir,
        f"{cancer}_oncoprint.svg",
    )

    print("Starting oncoprint analysis")
    print(f"  - Cancer type: {cancer}")
    print(f"  - Genes: {', '.join(genes)}")
    print(f"  - Data directory: {data_dir}")

    analysis = OncoprintAnalysis(
        snv_file=snv_path,
        cnv_file=cnv_path,
        genes=genes,
    )

    print("Building alteration matrix...")
    analysis.add_snv_data()
    analysis.add_cnv_data()
    analysis.refine_matrix()

    fisher_data = analysis.run_fisher_test(
        output_path=fisher_path,
    )

    analysis.plot_fisher_heatmap(
        fisher_data=fisher_data,
        output_path=heatmap_path,
    )

    analysis.plot_oncoprint(
        output_path=oncoprint_path,
    )

    print("Done.")


if __name__ == "__main__":
    main()
